### ISSUE TITLE
Dedication

### ISSUE THREAD

**Issue by vr8hub** [weijia-cheng/john-henry-newman_verses-on-various-occasions#1]
1. There really is only one valediction, just separated into two lines. Rather than using `<p>` and two valediction types, we typically just use a `<br/>` after the first line, similar to verse. And a span will handle the staired indenting as well. See Tom Jones for an example. Lint will probably complain, so you might need a lint ignore.
2. Same for the dateline.
3. I see the scan, so I know why you did it, but unless you have information to the contrary, I'm fairly sure that Newman's initials should all have periods, as normal. All of the scans of the original edition (1868) that I saw (Internet Archive) have periods, as do the 1880. If you look at [this](https://archive.org/details/a676839800newmuoft/page/n11/mode/2up) scan from 1889, you can start to see the _H_ period turn into a comma. I suspect they were making copies of copies, and it just degraded.
4. Not the dedication, but what about the epigraph on the title page, "cli pauca relicti…". Did you leave that out intentionally?

**Comment by weijia-cheng** [comment]
Thanks, I didn't notice the epigraph on the title page. That's been added in epigraph.xhtml.
