### ISSUE TITLE
Music XML files

### ISSUE THREAD

**Issue by vr8hub** [weijia-cheng/john-henry-newman_verses-on-various-occasions#3]
1. Per the discussion in the email thread, the XML files from Music Score should be in `/images`.

**Comment by weijia-cheng** [comment]
Thanks, didn't realize that they had to be in both. We should probably write a lint rule for that.

**Comment by vr8hub** [comment]
He mentioned in the email thread where y’all were discussing it. We don’t cover it in the manual at all, presumably because it doesn’t come up that often, but it’s been getting more often lately, so maybe we should add something.

I don’t know if lint can catch it; it would have to determine that an illustration is a music svg rather than a run-of-the-mill picture illustration.

**Comment by vr8hub** [comment]
And note that it's the _xml_ files that go in /images, not the svg's.

**Comment by weijia-cheng** [comment]
Oh, oof. That gets complicated; I didn't do a good job saving those. But I should be able to do that.

**Comment by weijia-cheng** [comment]
Ok, now I've added the XML files for real this time. There are fewer XML files than SVGs because in some cases multiple SVGs were generated from the same score.
