### ISSUE TITLE
Endnotes

### ISSUE THREAD

**Issue by vr8hub** [weijia-cheng/john-henry-newman_verses-on-various-occasions#4]
1. ~The one in "1 Pet." in endnote-5 should be a capitol-eye (I Pet.), I believe, looking at the scans. (That would also be consistent with what I usually see from Scripture quotations that use roman numerals for the chapters, they usually indicate the book with a roman numeral as well, e.g. I Corinthians, II Corinthians, etc.)~ done
2. ~Unless they're specifically used in the note, I don't think the endnotes need the leading text on them. The only reason it's there is because they didn't use a reference for those notes; the text is just to tell you where the note goes. Since we do have references, we already know where the note goes, so repeating the text is superfluous. There are a few exceptions, e.g. note 30, where the text is actually referred to, but those are rare.~ done, left it where the text is referred to in the note, or where it helps contextualize the musical score
3. ~There are a few capitalizations in the endnotes that don't appear to be necessary, e.g. Verses, Hymns, Author, etc.~ done
4. ~R. Hurrell needs an `<abbr class="name">` tag on his initial in endnote 12.~ done
5. Christe Pastorum is tagged in the title as Latin, but it's not tagged when it's mentioned in an endnote. I'm not sure that either is correct. We typically don't tag titles or proper names (see [section 8.2.9.2](https://standardebooks.org/manual/1.3.0/8-typography#8.2.9.2) of the manual). That means the title should probably not be tagged. For the endnote, I wonder whether the endnote should be tagged as a song title and quoted (see section 8.2.11). I don't know if this qualifies as a "short musical composition".
6. I'm not sure about the transliterated Greek language tags, either. You actually know more about this than I do, with the various Chinese tags. I would think that the straight `glc` language tag would be for actual Greek, i.e. using Greek letters. Or no? I am not only not an expert on this, I'm barely a beginner. :)
7. The Latin in note-25 is tagged with `span`s instead of italics. Is there a reason?
8. ~The "I" in "Canto I" in note-42 should be tagged as a roman numeral. Semanticate doesn't tag standalone I's since it can't tell the apart from normal I's, so they have to be handled manually.~ done
9. [Edit] There are a couple of mentions of specific breviaries in the endnotes. I believe those should be tagged as books.

**Comment by weijia-cheng** [comment]
I'll address the other issues a bit later, but I'll answer some of these questions--

re 6, my interpretation of [8.2.9.1](https://standardebooks.org/manual/1.3.0/8-typography#8.2.9.1) is that as long as the word is 1) not in English and 2) in Roman script, it should be italicized. As for the xml:lang attribute, I can't say for sure whether that is correct, but looking at [W3C](https://www.w3.org/International/questions/qa-when-xmllang), it doesn't seem concerned with the script that the text is in, just the natural language itself.
re 7, the spans are quotations from the poem itself, where those Latin phrases are not italicized. I'm not sure if this is strictly correct, but I figured if it was going to be a direct quote from the poem I would not italicize them. (Unless you think the Latin and Greek in the poem should be italicized too? I think that might be stepping too much on the toes of the original formatting, though.)
re 9, sure, though I am not sure if those should be italicized since that would bump into the ["holy text"](https://standardebooks.org/manual/1.3.0/8-typography#8.2.11.2) rule?

**Comment by vr8hub** [comment]
On #6, no, that's why I included the other sections. 8.2.9.2 and 8.2.11 specifically name exceptions to that rule.
On #7, I'm afraid that's probably an Alex question, too. On non-verse content, they would definitely be italicized (in both the endnotes and the poems themselves). Because the manual doesn't deliniate it, and because I haven't done a verse project myself, I'm not sure whether we make exceptions for this for verse. (Other than not modernizing spelling, which the manual _does_ cover.)
On #9, the holy texts rule mentions things like the Bible, the Koran, etc. I wouldn't think a hymn book qualifies. But as you know I've been wrong before. :)

**Comment by weijia-cheng** [comment]
Ok, looks like some of these questions will have to go to Alex. I'll fix the other things and come back to this later. As for the Breviary, I think it's more than a hymn book. In the context of Catholicism, it is, as I understand it, _the_ hymn book: https://en.wikipedia.org/wiki/Roman_Breviary

**Comment by vr8hub** [comment]
Yes, I know, but it's not a holy text, i.e. it's not Scripture. It's a book of songs.

**Comment by weijia-cheng** [comment]
Ok, I'll add that to the list of questions to punt upwards, but I think I don't think the distinction between "Scripture" and "a book of songs" is very clear in this case, especially not when much of the Breviary is the Psalms. Also, here's a style guide suggesting that "Roman Breviary" should not be italicized: https://www.csbsju.edu/Documents/SOT/admissions/style_guide.pdf

**Comment by vr8hub** [comment]
There’s a Grand Canyon-sized distinction between Scripture and a book of songs, at least in my circles. :) And someone else’s style guide doesn’t matter, only ours. (Well, technically the manual says we yield to CMS for things ours doesn’t cover.)

But to be clear, I don’t have a dog in the hunt, i.e. I don't feel strongly about it either way. I just raised a question based on what the manual says.

**Comment by vr8hub** [comment]
Also, just so it doesn't get lost, there are references to two breviaries, Roman and Parisian. I don't know the differences.

**Comment by weijia-cheng** [comment]
From Wikipedia, it seems that the Parisian Breviary is a reformed version of the Roman one. I suspect that either both should be italicized or neither.
