### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by vr8hub** [weijia-cheng/john-henry-newman_verses-on-various-occasions#5]
Running a check when doing a build (using either `-c` or `--check`) yields a slew of errors. It looks like they're confined to two main reasons:
1. In the endnotes, you used `epub:title` instead of `epub:type` throughout.
2. You have a few places where there's a block-level element inside a line-level element, e.g. a `<p>` inside a `<span>`. One of them was a href (`<a>`) inside a `<b>`.

The first one is easy, just a search and replace. You'll need to look at the other ones to see what needs to be done. When you're finished, use `-c` on your build will run `epubcheck` on the built epub to make sure it's legal. It's a good idea to use it on at least the final build before submitting for review. It takes a few seconds, so I may or may not use it all the time; I definitely don't for large projects, e.g. _War and Peace_.

**Comment by weijia-cheng** [comment]
Thanks, these should all be fixed now. Building with check passes.
